### PR TITLE
Implement drift correction

### PR DESCRIPTION
**Pull request by Balint817**
Makes cinema mod automatically correct drift, making the background stay in sync and letting charters to get a bit more creative

### CODE REVIEW

**Comment by ALLMarvelous** [comment]
You're gonna have to explain to me what drift is because I'm not even sure what that means

**Comment by Balint817** [comment]
Drift is how much it is out of sync.
Since no measures were taken to prevent it going out of sync, it isn't very surprising that it did.
Additionally, since the newest update, the game also occasionally freezes, potentially causing desyncs measurable in seconds.
If you're interested in how often Cinema desyncs, make a debug build, I added debug messages while testing it.

**Comment by ALLMarvelous** [comment]
I'll give this PR some testing

**Comment by ALLMarvelous** [comment]
Thanks for this PR. The initial purpose of Cinema was just to have a music video play in the background, so this sort of stuff never initially mattered to me. However, this change can make it easier for people to make gimmick charts with Cinema, so I will be merging this.

Gonna make a few changes to keep the new class in the style of the project and then I'll merge. Thanks again for taking the time.

**Review by ALLMarvelous — APPROVED** [review]
Good change

**Pull request merged**
